---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver 
    apt:
      name: apache2
      state: present
  - name: start webserver
    service: 
      name: apache2
      state: started

  - name: install amazon
    yum:
      name: httpd
      state: present
  - name: start amazon
    service:
       name: httpd
       state: started